# SPDX-License-Identifier: GPL-2.0-or-later
# Config Skyscraper — NextOS Black Retro Elite
[main]
inputFolder="/storage/roms"
gamelistFolder="/storage/roms"
videos="false"
symlink="false"
brackets="true"
maxLength="10000"
unattend="true"
verbosity="0"
hints="false"

# Portugues-BR primeiro, com fallback global
# Langs: https://github.com/muldjord/skyscraper/blob/master/docs/LANGUAGES.md
# Regions: https://github.com/muldjord/skyscraper/blob/master/docs/REGIONS.md
lang="pt"
langPrios="pt,en,es"
region="br"
regionPrios="br,wor,us,eu,jp"

[screenscraper]
userCreds="Username:Pass"
